export { Header } from './Header';
export { HeroSection } from './HeroSection';
export { FeaturesSection } from './FeaturesSection';
export { ProductoSection } from './ProductoSection';
export { PasosSection } from './PasosSection';
export { AboutSection } from './AboutSection';
export { ContactSection } from './ContactSection';
export { Footer } from './Footer';
export { Logo } from './Logo';
